apiVersion: v1
kind: Service
metadata:
    name: mysql-service
spec:
    type: ClusterIP
    selector:
        app: mysql
    ports:
        - name: mysql-port
          protocol: TCP
          port: 3306
          targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: mysql
    template:
        metadata:
            labels:
                app: mysql
        spec:
            volumes:
                - name: mysql-pv
                  persistentVolumeClaim:
                      claimName: mysql-pvc
            containers:
                - name: mysql
                  image: mysql-image
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 3306
                  volumeMounts:
                      - name: mysql-pv
                        mountPath: "/var/lib/mysql"
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: mysql-pv
    labels:
        type: local
spec:
    storageClassName: manual
    capacity:
        storage: 1Gi
    volumeMode: Filesystem
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: "/var/lib/mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mysql-pvc
    labels:
        app: mysql
spec:
    storageClassName: manual
    resources:
        requests:
            storage: 1Gi
    volumeMode: Filesystem
    accessModes:
        - ReadWriteOnce